// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://vuknaijjzkkputjbtnce.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ1a25haWpqemtrcHV0amJ0bmNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE0NjIzNDEsImV4cCI6MjA3NzAzODM0MX0.XHrb9s9mzB1pWEM5hip5zViUHWx3rHVUkwBGKsI9JI8";

class MockSupabase {
  auth = {
    signUp: async (credentials: any) => {
      console.log("[MockSupabase] signUp called for:", credentials.email);
      const user = {
        id: "mock-user-id-12345",
        email: credentials.email,
        user_metadata: credentials.options?.data || {},
        created_at: new Date().toISOString(),
      };
      const session = {
        access_token: "mock-token-xyz",
        token_type: "bearer",
        expires_in: 3600,
        refresh_token: "mock-refresh-xyz",
        user,
      };
      localStorage.setItem("mock_session", JSON.stringify(session));
      setTimeout(() => this._triggerAuthChange("SIGNED_IN", session), 50);
      return { data: { user, session }, error: null };
    },
    signInWithPassword: async (credentials: any) => {
      console.log("[MockSupabase] signInWithPassword called for:", credentials.email);
      const user = {
        id: "mock-user-id-12345",
        email: credentials.email,
        user_metadata: { full_name: "Developer User" },
        created_at: new Date().toISOString(),
      };
      const session = {
        access_token: "mock-token-xyz",
        token_type: "bearer",
        expires_in: 3600,
        refresh_token: "mock-refresh-xyz",
        user,
      };
      localStorage.setItem("mock_session", JSON.stringify(session));
      setTimeout(() => this._triggerAuthChange("SIGNED_IN", session), 50);
      return { data: { user, session }, error: null };
    },
    signOut: async () => {
      console.log("[MockSupabase] signOut called");
      localStorage.removeItem("mock_session");
      setTimeout(() => this._triggerAuthChange("SIGNED_OUT", null), 50);
      return { error: null };
    },
    getSession: async () => {
      const sessionStr = localStorage.getItem("mock_session");
      const session = sessionStr ? JSON.parse(sessionStr) : null;
      return { data: { session }, error: null };
    },
    onAuthStateChange: (callback: any) => {
      this.listeners.push(callback);
      const sessionStr = localStorage.getItem("mock_session");
      const session = sessionStr ? JSON.parse(sessionStr) : null;
      setTimeout(() => callback(session ? "SIGNED_IN" : "SIGNED_OUT", session), 0);
      return {
        data: {
          subscription: {
            unsubscribe: () => {
              this.listeners = this.listeners.filter(l => l !== callback);
            }
          }
        }
      };
    }
  };

  listeners: any[] = [];
  _triggerAuthChange(event: string, session: any) {
    this.listeners.forEach(l => l(event, session));
  }

  from(table: string) {
    let lastOperationData: any = null;
    let isMutation = false;

    const queryBuilder: any = {
      select: () => queryBuilder,
      insert: (data: any) => {
        console.log(`[MockSupabase] Inserted to ${table}:`, data);
        const list = this._getMockTableData(table);
        const newRecord = {
          id: Math.random().toString(36).substring(2, 9),
          created_at: new Date().toISOString(),
          ...data
        };
        list.unshift(newRecord);
        localStorage.setItem(`mock_table_${table}`, JSON.stringify(list));
        lastOperationData = newRecord;
        isMutation = true;
        return queryBuilder;
      },
      update: (data: any) => {
        console.log(`[MockSupabase] Updated in ${table}:`, data);
        if (table === 'profiles') {
          const current = this._getMockTableSingle('profiles') || {};
          const updated = { ...current, ...data };
          localStorage.setItem("mock_profile", JSON.stringify(updated));
          lastOperationData = updated;
        } else {
          lastOperationData = data;
        }
        isMutation = true;
        return queryBuilder;
      },
      upsert: (data: any) => {
        console.log(`[MockSupabase] Upserted in ${table}:`, data);
        if (table === 'profiles') {
          const current = this._getMockTableSingle('profiles') || {};
          const updated = { ...current, ...data };
          localStorage.setItem("mock_profile", JSON.stringify(updated));
          lastOperationData = updated;
        } else {
          lastOperationData = data;
        }
        isMutation = true;
        return queryBuilder;
      },
      delete: () => {
        isMutation = true;
        lastOperationData = {};
        return queryBuilder;
      },
      eq: () => queryBuilder,
      gte: () => queryBuilder,
      lte: () => queryBuilder,
      order: () => queryBuilder,
      single: () => {
        const data = isMutation ? lastOperationData : this._getMockTableSingle(table);
        return Promise.resolve({ data, error: null });
      },
      maybeSingle: () => {
        const data = isMutation ? lastOperationData : this._getMockTableSingle(table);
        return Promise.resolve({ data, error: null });
      },
      then: (onfulfilled: any) => {
        const resolvedValue = isMutation 
          ? { data: lastOperationData, error: null }
          : { data: this._getMockTableData(table), error: null };
        return Promise.resolve(resolvedValue).then(onfulfilled);
      }
    };
    return queryBuilder;
  }

  functions = {
    invoke: async (name: string, options: any) => {
      console.log(`[MockSupabase] Invoking function ${name} with options:`, options);
      if (name === 'google-fit-auth-url') {
        return { data: { authUrl: window.location.origin + "/oauth2-callback?code=mock-auth-code" }, error: null };
      }
      if (name === 'google-fit-callback') {
        const tokenKey = `mock_table_google_fit_tokens`;
        const defaultToken = [
          { id: "mock-token-id", user_id: "mock-user-id-12345", created_at: new Date().toISOString() }
        ];
        localStorage.setItem(tokenKey, JSON.stringify(defaultToken));
        return { data: { success: true }, error: null };
      }
      if (name === 'google-fit-sync') {
        const steps = Math.round(8000 + Math.random() * 4000);
        const calories = Math.round(1800 + Math.random() * 600);
        const heartRate = Math.round(65 + Math.random() * 20);
        const activeMinutes = Math.round(45 + Math.random() * 60);
        
        const fitnessRecord = {
          id: "mock-fit-id",
          user_id: "mock-user-id-12345",
          date: new Date().toISOString().split('T')[0],
          steps,
          calories,
          heart_rate: heartRate,
          active_minutes: activeMinutes,
          distance: Math.round(steps * 0.75),
        };
        localStorage.setItem("mock_fitness_data", JSON.stringify(fitnessRecord));
        return { data: { success: true }, error: null };
      }
      if (name === 'suggest-mood-foods') {
        return { 
          data: { 
            suggestions: [
              "A handful of walnuts and a banana for steady mood and energy booster.",
              "Green tea with a piece of dark chocolate to ease stress levels.",
              "Greek yogurt with berries for sustained energy release."
            ] 
          }, 
          error: null 
        };
      }
      if (name === 'analyze-food-photo') {
        return {
          data: {
            analysis: {
              total_calories: 350,
              protein: 15,
              carbs: 25,
              fats: 10,
              confidence: 88,
              food_items: ["Healthy Salad Bowl"]
            }
          },
          error: null
        };
      }
      return { data: { message: "Mock response" }, error: null };
    }
  };

  _getMockTableSingle(table: string) {
    if (table === 'profiles') {
      const stored = localStorage.getItem("mock_profile");
      if (stored) return JSON.parse(stored);
      
      const sessionStr = localStorage.getItem("mock_session");
      const session = sessionStr ? JSON.parse(sessionStr) : null;
      return { 
        id: session?.user?.id || "mock-user-id-12345", 
        full_name: session?.user?.user_metadata?.full_name || "Developer User", 
        weight: 73, 
        height: 176,
        age: 21,
        fitness_goals: "loose weight and gain muscles"
      };
    } 
    if (table === 'fitness_data') {
      const stored = localStorage.getItem("mock_fitness_data");
      if (stored) return JSON.parse(stored);
      
      return { 
        id: "mock-fit-id", 
        user_id: "mock-user-id-12345", 
        date: new Date().toISOString().split('T')[0], 
        steps: 9420, 
        calories: 1540,
        heart_rate: 72,
        active_minutes: 85,
        distance: 7000
      };
    }
    if (table === 'google_fit_tokens') {
      const stored = localStorage.getItem("mock_table_google_fit_tokens");
      if (stored) {
        const list = JSON.parse(stored);
        return list.length > 0 ? list[0] : null;
      }
      return null;
    }
    return null;
  }

  _getMockTableData(table: string) {
    const key = `mock_table_${table}`;
    const stored = localStorage.getItem(key);
    if (stored) return JSON.parse(stored);

    let defaultData: any[] = [];
    if (table === 'water_logs') {
      defaultData = [
        { id: "1", user_id: "mock-user-id-12345", glasses_logged: 2, timestamp: new Date().toISOString() },
        { id: "2", user_id: "mock-user-id-12345", glasses_logged: 1, timestamp: new Date(Date.now() - 3600000).toISOString() }
      ];
    } else if (table === 'meals') {
      defaultData = [
        { id: "1", user_id: "mock-user-id-12345", meal_name: "Oatmeal with Bananas", meal_type: "Breakfast", total_calories: 380, consumed_at: new Date().toISOString() },
        { id: "2", user_id: "mock-user-id-12345", meal_name: "Grilled Chicken Salad", meal_type: "Lunch", total_calories: 520, consumed_at: new Date(Date.now() - 14400000).toISOString() }
      ];
    } else if (table === 'mood_logs') {
      defaultData = [
        { id: "1", user_id: "mock-user-id-12345", mood: 4, energy_level: 4, stress_level: 3, notes: "Felt productive", date: new Date().toISOString().split('T')[0] }
      ];
    }
    localStorage.setItem(key, JSON.stringify(defaultData));
    return defaultData;
  }
}

const isDeadDomain = SUPABASE_URL.includes("vuknaijjzkkputjbtnce.supabase.co");

if (isDeadDomain) {
  console.warn("⚠️ The configured Supabase URL points to an unresolvable domain:", SUPABASE_URL);
  console.warn("⚠️ Offline Mock Mode has been automatically enabled for local development.");
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = isDeadDomain
  ? (new MockSupabase() as any)
  : createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      }
    });